package io.github.jvmspec.maven;

import io.github.jvmspec.discovery.DiscoveredSpec;
import io.github.jvmspec.discovery.SpecExample;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Generates the project-specific closed-world launcher and Native Image reflection metadata. */
final class NativeImageSourceGenerator {
    static final String GENERATED_PACKAGE = "io.github.jvmspec.generated";
    static final String GENERATED_SIMPLE_NAME = "JavaspecNativeMain";
    static final String GENERATED_QUALIFIED_NAME = GENERATED_PACKAGE + "." + GENERATED_SIMPLE_NAME;

    private NativeImageSourceGenerator() {
    }

    static PreparationResult write(
            List<DiscoveredSpec> specs,
            File basedir,
            File generatedSourcesRoot,
            File nativeImageConfigDir
    ) throws IOException {
        Objects.requireNonNull(specs, "specs must not be null");
        Objects.requireNonNull(basedir, "basedir must not be null");
        Objects.requireNonNull(generatedSourcesRoot, "generatedSourcesRoot must not be null");
        Objects.requireNonNull(nativeImageConfigDir, "nativeImageConfigDir must not be null");

        File launcherFile = new File(
                generatedSourcesRoot,
                GENERATED_PACKAGE.replace('.', File.separatorChar) + File.separator + GENERATED_SIMPLE_NAME + ".java"
        );
        File reflectionFile = new File(nativeImageConfigDir, "reflect-config.json");
        boolean launcherChanged = writeIfChanged(launcherFile, launcherSource(specs, basedir));
        boolean reflectionChanged = writeIfChanged(reflectionFile, reflectionConfiguration(specs));
        return new PreparationResult(launcherFile, reflectionFile, launcherChanged, reflectionChanged);
    }

    private static String launcherSource(List<DiscoveredSpec> specs, File basedir) throws IOException {
        StringBuilder source = new StringBuilder();
        source.append("package ").append(GENERATED_PACKAGE).append(";\n\n");
        source.append("import io.github.jvmspec.discovery.DiscoveredSpec;\n");
        source.append("import io.github.jvmspec.discovery.SpecExample;\n");
        source.append("import io.github.jvmspec.model.DescribedClass;\n");
        source.append("import io.github.jvmspec.nativeimage.NativeImageLauncher;\n\n");
        source.append("import java.io.File;\n");
        source.append("import java.util.ArrayList;\n");
        source.append("import java.util.List;\n\n");
        source.append("/** Generated by javaspec:native-prepare. Do not edit. */\n");
        source.append("public final class ").append(GENERATED_SIMPLE_NAME).append(" {\n");
        source.append("    private static final Class<?>[] LINKED_TYPES = new Class<?>[] {\n");
        List<String> linkedTypes = linkedTypes(specs);
        for (int i = 0; i < linkedTypes.size(); i++) {
            source.append("            ").append(linkedTypes.get(i)).append(".class");
            source.append(i + 1 < linkedTypes.size() ? ",\n" : "\n");
        }
        source.append("    };\n\n");
        source.append("    private ").append(GENERATED_SIMPLE_NAME).append("() { }\n\n");
        source.append("    public static void main(String[] args) {\n");
        source.append("        if (LINKED_TYPES.length == 0) {\n");
        source.append("            throw new IllegalStateException(\"No specification types were linked.\");\n");
        source.append("        }\n");
        source.append("        int exitCode = NativeImageLauncher.run(\n");
        source.append("                args, specs(), ").append(GENERATED_SIMPLE_NAME)
                .append(".class.getClassLoader(), System.out, System.err);\n");
        source.append("        if (exitCode != NativeImageLauncher.EXIT_OK) {\n");
        source.append("            System.exit(exitCode);\n");
        source.append("        }\n");
        source.append("    }\n\n");
        source.append("    private static List<DiscoveredSpec> specs() {\n");
        source.append("        List<DiscoveredSpec> specs = new ArrayList<DiscoveredSpec>();\n");
        for (int i = 0; i < specs.size(); i++) {
            appendSpec(source, specs.get(i), i, basedir);
        }
        source.append("        return specs;\n");
        source.append("    }\n");
        source.append("}\n");
        return source.toString();
    }

    private static void appendSpec(StringBuilder source, DiscoveredSpec spec, int index, File basedir)
            throws IOException {
        String variable = "examples" + index;
        source.append("        List<SpecExample> ").append(variable)
                .append(" = new ArrayList<SpecExample>();\n");
        List<SpecExample> examples = spec.exampleMetadata();
        for (int i = 0; i < examples.size(); i++) {
            SpecExample example = examples.get(i);
            source.append("        ").append(variable).append(".add(");
            if (SpecExample.displayNameFor(example.methodName()).equals(example.displayName())) {
                source.append("SpecExample.of(\"").append(javaString(example.methodName())).append("\", ")
                        .append(example.sourceOrderIndex()).append(", ").append(example.sourceLine()).append("));\n");
            } else {
                source.append("SpecExample.of(\"").append(javaString(example.methodName())).append("\", \"")
                        .append(javaString(example.displayName())).append("\", ")
                        .append(example.sourceOrderIndex()).append(", ").append(example.sourceLine()).append("));\n");
            }
        }
        source.append("        specs.add(DiscoveredSpec.of(\n");
        source.append("                new File(\"").append(javaString(relativePath(basedir, spec.specFile())))
                .append("\"),\n");
        source.append("                \"").append(javaString(spec.specQualifiedName())).append("\",\n");
        source.append("                DescribedClass.of(\"")
                .append(javaString(spec.describedClass().qualifiedName())).append("\"),\n");
        source.append("                ").append(variable).append("));\n");
    }

    private static List<String> linkedTypes(List<DiscoveredSpec> specs) {
        Set<String> types = new LinkedHashSet<String>();
        for (int i = 0; i < specs.size(); i++) {
            DiscoveredSpec spec = specs.get(i);
            types.add(spec.specQualifiedName());
            types.add(spec.describedClass().qualifiedName());
        }
        return new ArrayList<String>(types);
    }

    private static String reflectionConfiguration(List<DiscoveredSpec> specs) {
        Map<String, ReflectionAccess> accessByType = new LinkedHashMap<String, ReflectionAccess>();
        for (int i = 0; i < specs.size(); i++) {
            DiscoveredSpec spec = specs.get(i);
            merge(accessByType, spec.specQualifiedName(), ReflectionAccess.specification());
            merge(accessByType, spec.describedClass().qualifiedName(), ReflectionAccess.subject());
        }
        StringBuilder json = new StringBuilder();
        json.append("[\n");
        int index = 0;
        for (Map.Entry<String, ReflectionAccess> entry : accessByType.entrySet()) {
            ReflectionAccess access = entry.getValue();
            json.append("  {\n");
            json.append("    \"name\": \"").append(jsonString(entry.getKey())).append("\",\n");
            json.append("    \"allDeclaredConstructors\": true,\n");
            if (access.allDeclaredMethods) {
                json.append("    \"allDeclaredMethods\": true,\n");
            }
            json.append("    \"allPublicMethods\": true\n");
            json.append("  }");
            index++;
            json.append(index < accessByType.size() ? ",\n" : "\n");
        }
        json.append("]\n");
        return json.toString();
    }

    private static void merge(Map<String, ReflectionAccess> accessByType, String type, ReflectionAccess candidate) {
        ReflectionAccess existing = accessByType.get(type);
        if (existing == null) {
            accessByType.put(type, candidate);
            return;
        }
        accessByType.put(type, new ReflectionAccess(existing.allDeclaredMethods || candidate.allDeclaredMethods));
    }

    private static String relativePath(File basedir, File file) throws IOException {
        Path basePath = basedir.getCanonicalFile().toPath();
        Path filePath = file.getCanonicalFile().toPath();
        String value;
        if (filePath.startsWith(basePath)) {
            value = basePath.relativize(filePath).toString();
        } else {
            value = filePath.toString();
        }
        return value.replace(File.separatorChar, '/');
    }

    private static String javaString(String value) {
        return escaped(value);
    }

    private static String jsonString(String value) {
        return escaped(value);
    }

    private static String escaped(String value) {
        StringBuilder escaped = new StringBuilder();
        for (int i = 0; i < value.length(); i++) {
            char character = value.charAt(i);
            if (character == '\\') {
                escaped.append("\\\\");
            } else if (character == '"') {
                escaped.append("\\\"");
            } else if (character == '\n') {
                escaped.append("\\n");
            } else if (character == '\r') {
                escaped.append("\\r");
            } else if (character == '\t') {
                escaped.append("\\t");
            } else if (character < 0x20) {
                escaped.append(String.format("\\u%04x", Integer.valueOf(character)));
            } else {
                escaped.append(character);
            }
        }
        return escaped.toString();
    }

    private static boolean writeIfChanged(File file, String content) throws IOException {
        byte[] desired = content.getBytes(StandardCharsets.UTF_8);
        if (file.isFile()) {
            byte[] current = Files.readAllBytes(file.toPath());
            if (java.util.Arrays.equals(current, desired)) {
                return false;
            }
        }
        File parent = file.getParentFile();
        if (!parent.isDirectory() && !parent.mkdirs() && !parent.isDirectory()) {
            throw new IOException("Could not create directory: " + parent.getPath());
        }
        File temporary = File.createTempFile(file.getName(), ".tmp", parent);
        try {
            Files.write(temporary.toPath(), desired);
            try {
                Files.move(
                        temporary.toPath(),
                        file.toPath(),
                        StandardCopyOption.ATOMIC_MOVE,
                        StandardCopyOption.REPLACE_EXISTING
                );
            } catch (AtomicMoveNotSupportedException ex) {
                Files.move(temporary.toPath(), file.toPath(), StandardCopyOption.REPLACE_EXISTING);
            }
        } finally {
            if (temporary.exists()) {
                Files.delete(temporary.toPath());
            }
        }
        return true;
    }

    static final class PreparationResult {
        private final File launcherFile;
        private final File reflectionFile;
        private final boolean launcherChanged;
        private final boolean reflectionChanged;

        private PreparationResult(
                File launcherFile,
                File reflectionFile,
                boolean launcherChanged,
                boolean reflectionChanged
        ) {
            this.launcherFile = launcherFile;
            this.reflectionFile = reflectionFile;
            this.launcherChanged = launcherChanged;
            this.reflectionChanged = reflectionChanged;
        }

        File launcherFile() {
            return launcherFile;
        }

        File reflectionFile() {
            return reflectionFile;
        }

        boolean changed() {
            return launcherChanged || reflectionChanged;
        }
    }

    private static final class ReflectionAccess {
        private final boolean allDeclaredMethods;

        private ReflectionAccess(boolean allDeclaredMethods) {
            this.allDeclaredMethods = allDeclaredMethods;
        }

        private static ReflectionAccess specification() {
            return new ReflectionAccess(false);
        }

        private static ReflectionAccess subject() {
            return new ReflectionAccess(true);
        }
    }
}
