package org.javaspec.generation;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Generates Java source code for typed Prophecy wrapper classes.
 * <p>
 * Given an interface class {@code Mailer}, generates {@code MailerProphecy}
 * that extends {@code BaseObjectProphecy<Mailer>} with typed delegation methods.
 * </p>
 */
public final class ProphecySkeletonGenerator {

    private ProphecySkeletonGenerator() {
    }

    /**
     * Generates the source code for a prophecy wrapper class.
     *
     * @param interfaceType the interface type to wrap
     * @param packageName   the target package name (may be empty for default package)
     * @return the generated Java source code
     */
    public static String render(Class<?> interfaceType, String packageName) {
        Objects.requireNonNull(interfaceType, "interfaceType must not be null");
        if (!interfaceType.isInterface()) {
            throw new IllegalArgumentException("Prophecy wrappers require an interface type, got: "
                    + interfaceType.getName());
        }
        String simpleName = interfaceType.getSimpleName();
        String wrapperSimpleName = simpleName + "Prophecy";

        StringBuilder builder = new StringBuilder();

        if (packageName.length() > 0) {
            builder.append("package ").append(packageName).append(";\n\n");
        }

        builder.append("import org.javaspec.doubles.prophecy.BaseObjectProphecy;\n");
        builder.append("import org.javaspec.doubles.prophecy.MethodProphecy;\n");
        builder.append("import org.javaspec.doubles.prophecy.PredictionRegistry;\n");
        builder.append("import org.javaspec.doubles.InterfaceDouble;\n");
        builder.append("\n");

        builder.append("/**\n");
        builder.append(" * Typed prophecy wrapper for {@link ").append(simpleName).append("}.\n");
        builder.append(" * Generated by javaspec.\n");
        builder.append(" */\n");
        builder.append("public final class ").append(wrapperSimpleName)
                .append(" extends BaseObjectProphecy<").append(simpleName).append("> {\n");

        builder.append("\n");
        builder.append("    /**\n");
        builder.append("     * Creates a new prophecy wrapper.\n");
        builder.append("     *\n");
        builder.append("     * @param interfaceDouble the typed double handle\n");
        builder.append("     * @param registry        the prediction registry (may be null)\n");
        builder.append("     */\n");
        builder.append("    public ").append(wrapperSimpleName)
                .append("(InterfaceDouble<").append(simpleName).append("> interfaceDouble, PredictionRegistry registry) {\n");
        builder.append("        super(interfaceDouble, registry);\n");
        builder.append("    }\n");

        Method[] methods = interfaceType.getMethods();
        boolean first = true;
        for (Method method : methods) {
            if (shouldSkip(method)) {
                continue;
            }
            if (first) {
                builder.append("\n");
                first = false;
            }
            appendMethod(builder, method, simpleName);
        }

        builder.append("}\n");
        return builder.toString();
    }

    private static boolean shouldSkip(Method method) {
        int modifiers = method.getModifiers();
        if (Modifier.isStatic(modifiers)) {
            return true;
        }
        if (Modifier.isFinal(modifiers)) {
            return true;
        }
        if (Modifier.isPrivate(modifiers)) {
            return true;
        }
        // Skip methods from Object (toString, equals, hashCode, etc.)
        try {
            Object.class.getMethod(method.getName(), method.getParameterTypes());
            return true;
        } catch (NoSuchMethodException e) {
            return false;
        }
    }

    private static void appendMethod(StringBuilder builder, Method method, String interfaceSimpleName) {
        String methodName = method.getName();
        Class<?> returnType = method.getReturnType();
        Class<?>[] paramTypes = method.getParameterTypes();
        String[] paramNames = parameterNames(method);

        String boxedReturnType = boxedType(returnType);

        builder.append("\n");
        builder.append("    /**\n");
        builder.append("     * Prophesizes a call to {@code ").append(interfaceSimpleName)
                .append("#").append(methodName).append("(...)}.\n");
        builder.append("     *\n");
        builder.append("     * @return a method prophecy for chaining stubs and predictions\n");
        builder.append("     */\n");

        if ("void".equals(boxedReturnType)) {
            builder.append("    public MethodProphecy<Void> ").append(methodName).append("(");
        } else {
            builder.append("    public MethodProphecy<").append(boxedReturnType).append("> ").append(methodName).append("(");
        }

        for (int i = 0; i < paramTypes.length; i++) {
            if (i > 0) {
                builder.append(", ");
            }
            builder.append(paramTypes[i].getName()).append(" ").append(paramNames[i]);
        }
        builder.append(") {\n");

        if ("void".equals(boxedReturnType)) {
            builder.append("        return method(\"").append(methodName).append("\"");
        } else {
            builder.append("        return method(\"").append(methodName).append("\"");
        }

        for (int i = 0; i < paramTypes.length; i++) {
            builder.append(", ");
            builder.append(paramNames[i]);
        }
        builder.append(");\n");
        builder.append("    }\n");
    }

    private static String[] parameterNames(Method method) {
        // Java reflection doesn't give us parameter names by default (requires -parameters flag)
        // We generate synthetic names: arg0, arg1, etc.
        Class<?>[] paramTypes = method.getParameterTypes();
        String[] names = new String[paramTypes.length];
        for (int i = 0; i < names.length; i++) {
            names[i] = "arg" + i;
        }
        return names;
    }

    private static String boxedType(Class<?> type) {
        if (!type.isPrimitive()) {
            return type.getName();
        }
        if (boolean.class.equals(type)) return "Boolean";
        if (byte.class.equals(type)) return "Byte";
        if (short.class.equals(type)) return "Short";
        if (int.class.equals(type)) return "Integer";
        if (long.class.equals(type)) return "Long";
        if (float.class.equals(type)) return "Float";
        if (double.class.equals(type)) return "Double";
        if (char.class.equals(type)) return "Character";
        return "Void";
    }
}
