#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(cd "${script_dir}/.." && pwd -P)"
cd "$repo_root"
export LC_ALL=C

output="${1:-docs/history/api-baseline-1.0.0.md}"

if ! command -v javap >/dev/null 2>&1; then
  printf 'ERROR: javap is required to generate the API baseline.\n' >&2
  exit 1
fi

version="$(awk '
  /^[[:space:]]*<version>[[:space:]]*[^<]+[[:space:]]*<\/version>[[:space:]]*$/ {
    line = $0
    sub(/^[[:space:]]*<version>[[:space:]]*/, "", line)
    sub(/[[:space:]]*<\/version>[[:space:]]*$/, "", line)
    print line
    exit
  }
' pom.xml)"

modules=(
  "Core|target/classes"
  "Maven plugin|javaspec-maven-plugin/target/classes"
  "JUnit Platform engine|javaspec-junit-platform-engine/target/classes"
  "Bytecode doubles|javaspec-bytecode-doubles/target/classes"
  "Bytecode agent|javaspec-bytecode-agent/target/classes"
  "Gradle plugin|javaspec-gradle-plugin/build/classes/java/main"
)

for module in "${modules[@]}"; do
  classes_dir="${module#*|}"
  if [ ! -d "$classes_dir" ]; then
    printf 'ERROR: %s is missing. Run scripts/verify-all.sh before generating the baseline.\n' "$classes_dir" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "$output")"
temporary="$(mktemp "${output}.tmp.XXXXXX")"
trap 'rm -f "$temporary"' EXIT

{
  printf '# javaspec 1.0 API baseline\n\n'
  printf 'Generated by `scripts/generate-api-baseline.sh` from aligned version `%s`.\n\n' "$version"
  printf 'This inventory records public/protected JVM signatures for every externally visible class in\n'
  printf 'the shipped artifacts. Compatibility guarantees still follow the classifications in\n'
  printf '`docs/api-surface-1.0.md`; inclusion here does not promote `INTERNAL` types to supported API.\n\n'

  for module in "${modules[@]}"; do
    label="${module%%|*}"
    classes_dir="${module#*|}"
    printf '## %s\n\n```text\n' "$label"

    while IFS= read -r -d '' class_file; do
      if javap -verbose "$class_file" | awk '
        /^  flags:/ && /ACC_PUBLIC/ { public_type = 1 }
        END { exit public_type ? 0 : 1 }
      '; then
        javap -protected -s "$class_file" \
          | awk '!/^Compiled from /'
        printf '\n'
      fi
    done < <(find "$classes_dir" -name '*.class' -print0 | sort -z)

    printf '```\n\n'
  done
} > "$temporary"

mv "$temporary" "$output"
trap - EXIT
printf 'PASS: API baseline generated at %s for version %s.\n' "$output" "$version"
